import {ArrowRight,Clock3,Headphones,ShieldCheck,Sparkles,Truck} from 'lucide-react';import {Link} from 'react-router-dom';import CategoryCard from '../../components/CategoryCard';import ProductCard from '../../components/ProductCard';import OfferCard from '../../components/OfferCard';import useApiCollection from '../../hooks/useApiCollection';
export default function Home(){const {data:products}=useApiCollection('/api/products');const categories=[];return <>
 <section className="hero section-wrap"><div className="hero-copy"><span className="hero-kicker"><Sparkles/> Fresh from local farms</span><h1>Fresh groceries,<br/><em>delivered happy.</em></h1><p>From farm-fresh produce to everyday essentials, get everything your home loves delivered right to your door.</p><div className="hero-actions"><Link className="btn btn-primary btn-large" to="/categories">Shop now <ArrowRight/></Link><Link className="btn btn-light btn-large" to="/offers">View offers</Link></div><div className="hero-meta"><span><b>4.9</b> customer rating</span><span><b>30 min</b> express delivery</span></div></div><div className="hero-visual"><div className="hero-photo"><img src="https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=85" alt="Fresh grocery aisle"/></div><div className="floating-card floating-top"><span>🥬</span><div><b>Always fresh</b><small>Quality checked daily</small></div></div><div className="floating-card floating-bottom"><span>✓</span><div><b>Order confirmed!</b><small>Arriving in 28 minutes</small></div></div></div></section>
 <section className="benefit-strip"><div><Truck/><b>Free delivery</b><span>On orders over $50</span></div><div><Clock3/><b>Same-day delivery</b><span>Order before 5 PM</span></div><div><ShieldCheck/><b>Secure payment</b><span>100% protected checkout</span></div><div><Headphones/><b>Here to help</b><span>Support 7 days a week</span></div></section>
 <section className="section section-wrap"><div className="section-heading"><div><span className="eyebrow">Shop your way</span><h2>Explore our categories</h2><p>All your weekly essentials, organized for an easier shop.</p></div><Link to="/categories">View all <ArrowRight/></Link></div><div className="category-grid">{categories.map(c=><CategoryCard key={c.id} category={c}/>)}</div></section>
 <section className="section section-soft"><div className="section-wrap"><div className="section-heading"><div><span className="eyebrow">Customer favorites</span><h2>Fresh picks for you</h2><p>Hand-picked products our community is loving this week.</p></div><Link to="/categories">Shop all products <ArrowRight/></Link></div><div className="product-grid">{products.slice(0,8).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
 <section className="section section-wrap"><div className="section-heading"><div><span className="eyebrow">Limited time</span><h2>Offers too good to miss</h2></div><Link to="/offers">See every offer <ArrowRight/></Link></div><div className="offers-row">{products.filter(p=>p.discount).slice(0,3).map(p=><OfferCard key={p.id} product={p}/>)}</div></section>
 <section className="why section-wrap"><div className="why-photo"><img src="https://images.unsplash.com/photo-1579113800032-c38bd7635818?auto=format&fit=crop&w=1000&q=80" alt="Fresh produce"/></div><div className="why-copy"><span className="eyebrow">The TNT difference</span><h2>Good food starts with good choices.</h2><p>We make those choices easier with quality you can trust, prices you'll love, and service that feels genuinely local.</p><div className="why-list">{[['01','Fresh, guaranteed','Every item is quality checked before it reaches you.'],['02','Prices that make sense','Great everyday value, with no hidden fees.'],['03','People who care','Friendly local support whenever you need us.']].map(x=><div key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span></div>)}</div></div></section>
 <section className="newsletter"><span>Stay in the fresh loop</span><h2>Deals, recipes & goodness.<br/>Straight to your inbox.</h2><form onSubmit={e=>e.preventDefault()}><input type="email" placeholder="Enter your email address"/><button className="btn btn-dark">Subscribe <ArrowRight/></button></form><small>No spam. Just the good stuff. Unsubscribe anytime.</small></section>
 </>}
