import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { api, downloadCsv } from './api.js';

const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/api';
const IDENTITY = `${API}/identity`;
const CATALOG = `${API}/catalog`;
const ORDER = `${API}/order`;
const key = () => crypto.randomUUID();

function App() {
  const [products, setProducts] = useState([]), [categories, setCategories] = useState([]), [q, setQ] = useState(''), [categoryId, setCategoryId] = useState('');
  const [token, setToken] = useState(localStorage.getItem('marketflowToken') || ''), [user, setUser] = useState(JSON.parse(localStorage.getItem('marketflowUser') || 'null'));
  const [view, setView] = useState('browse'), [message, setMessage] = useState(''), [selectedProduct, setSelectedProduct] = useState('');
  const headers = token ? { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' } : { 'Content-Type': 'application/json' };
  const customer = user?.roles?.includes('Customer'), staff = user?.roles?.some(x => ['CatalogStaff', 'InventoryStaff', 'OperationsAdmin'].includes(x)), admin = user?.roles?.includes('OperationsAdmin');
  const loadProducts = () => api(`${CATALOG}/products?${new URLSearchParams({ q, ...(categoryId && { categoryId }), page: '1', pageSize: '50' })}`).then(setProducts).catch(e => setMessage(e.message));
  useEffect(() => { api(`${CATALOG}/categories`).then(setCategories).catch(e => setMessage(e.message)); }, []);
  useEffect(loadProducts, [q, categoryId]);
  const signedIn = result => { localStorage.setItem('marketflowToken', result.accessToken); localStorage.setItem('marketflowUser', JSON.stringify(result.user)); setToken(result.accessToken); setUser(result.user); setView(result.user.roles.includes('Customer') ? 'basket' : 'manage'); setMessage('Signed in successfully.'); };
  const logout = async () => { try { await api(`${IDENTITY}/auth/logout`, { method: 'POST', headers }); } catch {} localStorage.removeItem('marketflowToken'); localStorage.removeItem('marketflowUser'); setToken(''); setUser(null); setView('browse'); };
  return <main><header><div><span className="mark">M</span><strong>Marketflow</strong><small>Fresh essentials, simply managed.</small></div><nav><button onClick={() => setView('browse')}>Browse</button>{customer && <><button onClick={() => setView('basket')}>Basket</button><button onClick={() => setView('addresses')}>Addresses</button><button onClick={() => setView('orders')}>My orders</button></>}{staff && <><button onClick={() => setView('manage')}>Products</button><button onClick={() => setView('inventory')}>Inventory</button></>}{admin && <><button onClick={() => setView('sales')}>Sales</button><button onClick={() => setView('staffOrders')}>Orders</button></>}{user ? <button className="primary" onClick={logout}>Sign out</button> : <button className="primary" onClick={() => setView('login')}>Sign in</button>}</nav></header>{message && <p className="notice" role="alert">{message}<button onClick={() => setMessage('')}>×</button></p>}
    {view === 'login' && <Login onSuccess={signedIn} onError={setMessage}/>} {view === 'browse' && <Browse products={products} categories={categories} q={q} setQ={setQ} categoryId={categoryId} setCategoryId={setCategoryId} canAdd={customer} headers={headers} onAdded={() => setMessage('Added to basket.')} onSelect={id => { setSelectedProduct(id); setView('product'); }} onError={setMessage}/>} {view === 'product' && <ProductDetail id={selectedProduct} canAdd={customer} headers={headers} onAdded={() => setMessage('Added to basket.')} onBack={() => setView('browse')} onError={setMessage}/>} {view === 'basket' && customer && <Basket headers={headers} onError={setMessage} onCheckout={() => setView('orders')}/>} {view === 'addresses' && customer && <Addresses headers={headers} onError={setMessage}/>} {view === 'orders' && customer && <Orders headers={headers} onError={setMessage}/>} {view === 'manage' && staff && <Manage headers={headers} categories={categories} onChanged={loadProducts} onError={setMessage}/>} {view === 'inventory' && staff && <Inventory headers={headers} categories={categories} onError={setMessage}/>} {view === 'sales' && admin && <Sales headers={headers} onError={setMessage}/>} {view === 'staffOrders' && admin && <StaffOrders headers={headers} onError={setMessage}/>}</main>;
}
function Login({ onSuccess, onError }) { const [register, setRegister] = useState(false), [email, setEmail] = useState(register ? '' : 'customer@marketflow.local'), [password, setPassword] = useState(register ? '' : 'ChangeMe!123'), [displayName, setDisplayName] = useState(''); const submit = async e => { e.preventDefault(); try { onSuccess(await api(`${IDENTITY}/auth/${register ? 'register' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(register ? { email, displayName, password } : { email, password }) })); } catch (x) { onError(x.message); } }; return <section className="panel"><h1>{register ? 'Create customer account' : 'Sign in'}</h1><form onSubmit={submit}>{register && <label>Name<input value={displayName} onChange={e => setDisplayName(e.target.value)} required/></label>}<label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required/></label><button className="primary">{register ? 'Create account' : 'Sign in'}</button></form><button onClick={() => { setRegister(!register); setEmail(register ? 'customer@marketflow.local' : ''); setPassword(register ? 'ChangeMe!123' : ''); }}> {register ? 'Use existing account' : 'Create customer account'} </button></section>; }
function Browse({ products, categories, q, setQ, categoryId, setCategoryId, canAdd, headers, onAdded, onSelect, onError }) { const add = async id => { try { const basket = await api(`${ORDER}/basket`, { headers }); const existing = basket.lines.find(x => x.productId === id); await api(`${ORDER}/basket/items/${id}`, { method: 'PUT', headers, body: JSON.stringify({ quantity: (existing?.quantity || 0) + 1 }) }); onAdded(); } catch (e) { onError(e.message); } }; return <section><div className="hero"><p>THE DAILY MARKET</p><h1>Find what your kitchen needs.</h1><span>Search current products and see availability before checkout.</span></div><div className="filters"><input aria-label="Search products" placeholder="Search product name or SKU" value={q} onChange={e => setQ(e.target.value)}/><select value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">All categories</option>{categories.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="grid">{products.map(p => <article key={p.id}><div className="image">{p.name.slice(0, 1)}</div><p>{p.category.name}</p><h2>{p.name}</h2><strong>${Number(p.price).toFixed(2)}</strong><span className={p.available ? 'available' : 'unavailable'}>{p.available ? 'In stock' : 'Unavailable'}</span><button onClick={() => onSelect(p.id)}>View details</button>{canAdd && p.available && <button className="primary" onClick={() => add(p.id)}>Add to basket</button>}</article>)}{!products.length && <p>No products match your search.</p>}</div></section>; }
function ProductDetail({ id, canAdd, headers, onAdded, onBack, onError }) { const [product, setProduct] = useState(null); useEffect(() => { api(`${CATALOG}/products/${id}`).then(setProduct).catch(e => onError(e.message)); }, [id]); const add = async () => { try { const basket = await api(`${ORDER}/basket`, { headers }); const existing = basket.lines.find(x => x.productId === id); await api(`${ORDER}/basket/items/${id}`, { method: 'PUT', headers, body: JSON.stringify({ quantity: (existing?.quantity || 0) + 1 }) }); onAdded(); } catch (e) { onError(e.message); } }; if (!product) return <section className="panel">Loading product…</section>; return <section className="panel"><button onClick={onBack}>Back to products</button><h1>{product.name}</h1><p>{product.category?.name}</p><p>{product.description || 'No product description provided.'}</p><h2>${Number(product.price).toFixed(2)}</h2><p>{product.available ? `${product.stockQuantity} available` : 'Unavailable'}</p>{canAdd && product.available && <button className="primary" onClick={add}>Add to basket</button>}</section>; }
function Addresses({ headers, onError }) { const [rows, setRows] = useState([]), blank = { recipientName: '', phone: '', line1: '', line2: '', city: '', zone: '' }, [form, setForm] = useState(blank), [editing, setEditing] = useState(null); const load = () => api(`${ORDER}/addresses`, { headers }).then(setRows).catch(e => onError(e.message)); useEffect(load, []); const submit = async e => { e.preventDefault(); try { await api(editing ? `${ORDER}/addresses/${editing}` : `${ORDER}/addresses`, { method: editing ? 'PUT' : 'POST', headers, body: JSON.stringify(form) }); setForm(blank); setEditing(null); load(); } catch (x) { onError(x.message); } }; const remove = async id => { if (!confirm('Delete this saved address?')) return; try { await api(`${ORDER}/addresses/${id}`, { method: 'DELETE', headers }); load(); } catch (e) { onError(e.message); } }; return <section className="panel"><h1>Saved addresses</h1><form onSubmit={submit}>{Object.entries(form).map(([name, value]) => <label key={name}>{name.replace(/([A-Z])/g, ' $1')}<input value={value} onChange={e => setForm({ ...form, [name]: e.target.value })} required={name !== 'line2'}/></label>)}<button className="primary">{editing ? 'Save address' : 'Add address'}</button></form><table><tbody>{rows.map(a => <tr key={a.id}><td>{a.recipientName}<br/><small>{a.line1}, {a.city} · {a.zone}</small></td><td><button onClick={() => { setEditing(a.id); setForm(a); }}>Edit</button><button onClick={() => remove(a.id)}>Delete</button></td></tr>)}</tbody></table></section>; }
function Basket({ headers, onError, onCheckout }) { const [basket, setBasket] = useState(null), [addresses, setAddresses] = useState([]), [addressId, setAddressId] = useState(''); const load = () => { api(`${ORDER}/basket`, { headers }).then(setBasket).catch(e => onError(e.message)); api(`${ORDER}/addresses`, { headers }).then(x => { setAddresses(x); if (!addressId && x[0]) setAddressId(x[0].id); }).catch(e => onError(e.message)); }; useEffect(load, []); const change = async (id, quantity) => { try { if (quantity <= 0) await api(`${ORDER}/basket/items/${id}`, { method: 'DELETE', headers }); else await api(`${ORDER}/basket/items/${id}`, { method: 'PUT', headers, body: JSON.stringify({ quantity }) }); load(); } catch (e) { onError(e.message); } }; const checkout = async () => { try { if (!addressId) throw new Error('Create and select a delivery address first.'); const result = await api(`${ORDER}/orders`, { method: 'POST', headers: { ...headers, 'Idempotency-Key': key() }, body: JSON.stringify({ addressId }) }); onError(`Order ${result.orderId} is ${result.status}.`); onCheckout(); } catch (e) { onError(e.message); } }; if (!basket) return <section className="panel">Loading basket…</section>; return <section className="panel"><h1>Your basket</h1>{basket.lines.map(x => <p key={x.productId}><strong>{x.name || 'Unavailable product'}</strong> × <button onClick={() => change(x.productId, x.quantity - 1)}>−</button>{x.quantity}<button onClick={() => change(x.productId, x.quantity + 1)}>+</button> — ${Number(x.lineTotal || 0).toFixed(2)}</p>)}{!basket.lines.length && <p>Your basket is empty.</p>}<p>Subtotal: ${Number(basket.subtotal).toFixed(2)} · Tax: ${Number(basket.tax).toFixed(2)} · Delivery: ${Number(basket.deliveryFee).toFixed(2)}</p><h2>Total: ${Number(basket.total).toFixed(2)}</h2><select value={addressId} onChange={e => setAddressId(e.target.value)}><option value="">Choose address</option>{addresses.map(x => <option key={x.id} value={x.id}>{x.line1}, {x.city}</option>)}</select><button className="primary" disabled={!basket.lines.length} onClick={checkout}>Place order</button></section>; }
function Orders({ headers, onError }) { const [rows, setRows] = useState([]); useEffect(() => { api(`${ORDER}/orders`, { headers }).then(setRows).catch(e => onError(e.message)); }, []); return <section className="panel"><h1>My orders</h1><table><thead><tr><th>Order</th><th>Status</th><th>Total</th><th>Created</th></tr></thead><tbody>{rows.map(o => <tr key={o.id}><td>{o.id.slice(0, 8)}</td><td>{o.status}</td><td>${Number(o.total).toFixed(2)}</td><td>{new Date(o.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!rows.length && <p>No orders yet.</p>}</section>; }
function Manage({ headers, categories, onChanged, onError }) { const blank = { sku: '', name: '', description: '', price: '', stockQuantity: '', categoryId: categories[0]?.id || '' }, [form, setForm] = useState(blank), [items, setItems] = useState([]), [editing, setEditing] = useState(null); const load = () => api(`${CATALOG}/staff/products`, { headers }).then(setItems).catch(e => onError(e.message)); useEffect(load, []); const submit = async e => { e.preventDefault(); try { const data = { ...form, price: Number(form.price), stockQuantity: Number(form.stockQuantity) }; await api(editing ? `${CATALOG}/products/${editing}` : `${CATALOG}/products`, { method: editing ? 'PUT' : 'POST', headers, body: JSON.stringify(data) }); setForm(blank); setEditing(null); load(); onChanged(); } catch (x) { onError(x.message); } }; return <section className="panel"><h1>{editing ? 'Edit product' : 'Add product'}</h1><form onSubmit={submit}>{Object.entries(form).map(([name, value]) => name === 'categoryId' ? <label key={name}>Category<select value={value} onChange={e => setForm({ ...form, categoryId: e.target.value })}>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label> : <label key={name}>{name}<input type={name === 'price' || name === 'stockQuantity' ? 'number' : 'text'} value={value} onChange={e => setForm({ ...form, [name]: e.target.value })} required={name !== 'description'}/></label>)}<button className="primary">Save product</button></form><table><tbody>{items.map(p => <tr key={p.id}><td>{p.name}</td><td>{p.stockQuantity}</td><td>{p.active ? 'Active' : 'Inactive'}</td><td>{p.active && <><button onClick={() => { setEditing(p.id); setForm({ sku: p.sku, name: p.name, description: p.description || '', price: p.price, stockQuantity: p.stockQuantity, categoryId: p.category.id }); }}>Edit</button><button onClick={async () => { await api(`${CATALOG}/products/${p.id}/deactivate`, { method: 'PATCH', headers }); load(); }}>Deactivate</button></>}</td></tr>)}</tbody></table></section>; }
function Inventory({ headers, categories, onError }) { const [report, setReport] = useState(null), [threshold, setThreshold] = useState(5), [categoryId, setCategoryId] = useState(''); const load = async () => { try { setReport(await api(`${CATALOG}/reports/inventory?${new URLSearchParams({ threshold, ...(categoryId && { categoryId }) })}`, { headers })); } catch (e) { onError(e.message); } }; return <section className="panel"><h1>Inventory report</h1><div className="filters"><select value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">All categories</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="number" min="0" value={threshold} onChange={e => setThreshold(e.target.value)}/><button className="primary" onClick={load}>Run report</button><button onClick={() => downloadCsv(`${CATALOG}/reports/inventory/export?${new URLSearchParams({ threshold, ...(categoryId && { categoryId }) })}`, headers, 'inventory-report.csv').catch(e => onError(e.message))}>Download CSV</button></div>{report && <ReportTable report={report}/>}</section>; }
function Sales({ headers, onError }) { const [report, setReport] = useState(null), [from, setFrom] = useState(''), [to, setTo] = useState(''), [status, setStatus] = useState(''); const load = async () => { try { setReport(await api(`${ORDER}/reports/sales?${new URLSearchParams({ ...(from && { from: new Date(from).toISOString() }), ...(to && { to: new Date(to).toISOString() }), ...(status && { status }) })}`, { headers })); } catch (e) { onError(e.message); } }; return <section className="panel"><h1>Sales report</h1><div className="filters"><input type="date" value={from} onChange={e => setFrom(e.target.value)}/><input type="date" value={to} onChange={e => setTo(e.target.value)}/><select value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option>Confirmed</option><option>Cancelled</option><option>Rejected</option></select><button className="primary" onClick={load}>Run report</button><button onClick={() => downloadCsv(`${CATALOG}/reports/inventory/export?${new URLSearchParams({ threshold, ...(categoryId && { categoryId }) })}`, headers, 'inventory-report.csv').catch(e => onError(e.message))}>Download CSV</button></div>{report && <><p>{report.orderCount} orders · recognized sales ${Number(report.recognizedSales).toFixed(2)} · tax ${Number(report.tax).toFixed(2)}</p><table><tbody>{report.orders.map(o => <tr key={o.id}><td>{o.id.slice(0, 8)}</td><td>{o.status}</td><td>${Number(o.total).toFixed(2)}</td></tr>)}</tbody></table></>}</section>; }
function StaffOrders({ headers, onError }) { const [rows, setRows] = useState([]); const load = () => api(`${ORDER}/staff/orders`, { headers }).then(setRows).catch(e => onError(e.message)); useEffect(load, []); const cancel = async id => { const reason = prompt('Cancellation reason'); if (!reason) return; try { await api(`${ORDER}/staff/orders/${id}/cancel`, { method: 'POST', headers, body: JSON.stringify({ reason }) }); load(); } catch (e) { onError(e.message); } }; return <section className="panel"><h1>Order operations</h1><table><tbody>{rows.map(o => <tr key={o.id}><td>{o.id.slice(0, 8)}</td><td>{o.status}</td><td>${Number(o.total).toFixed(2)}</td><td>{o.status === 'Confirmed' && <button onClick={() => cancel(o.id)}>Cancel</button>}</td></tr>)}</tbody></table></section>; }
function ReportTable({ report }) { return <><p>{report.totalProducts} products · {report.lowStockCount} low stock · {report.zeroStockCount} out of stock</p><table><tbody>{report.products.map(p => <tr key={p.sku}><td>{p.sku}</td><td>{p.name}</td><td>{p.stockQuantity}</td><td>{p.lowStock ? 'Low' : ''}</td></tr>)}</tbody></table></>; }
createRoot(document.getElementById('root')).render(<App/>);
